#!/bin/bash
# Build Script - Compile Each Contract Individually
# Generated by Immunefi Instascope

set -e

echo "Building 101 contracts individually..."
echo ""

echo "Building AliceV2PositionParser (contract_AliceV2PositionParser_ef3b)"
FOUNDRY_PROFILE=contract_AliceV2PositionParser_ef3b forge build || {
  echo "❌ Failed to build AliceV2PositionParser"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_AliceV2PositionParser_ef3b forge build"
}
echo "✅ Built AliceV2PositionParser"
echo ""

echo "Building AliceV2PositionLib (contract_AliceV2PositionLib_a286)"
FOUNDRY_PROFILE=contract_AliceV2PositionLib_a286 forge build || {
  echo "❌ Failed to build AliceV2PositionLib"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_AliceV2PositionLib_a286 forge build"
}
echo "✅ Built AliceV2PositionLib"
echo ""

echo "Building BebopBlendAdapter (contract_BebopBlendAdapter_901c)"
FOUNDRY_PROFILE=contract_BebopBlendAdapter_901c forge build || {
  echo "❌ Failed to build BebopBlendAdapter"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_BebopBlendAdapter_901c forge build"
}
echo "✅ Built BebopBlendAdapter"
echo ""

echo "Building ZeroExV4Adapter (contract_ZeroExV4Adapter_49af)"
FOUNDRY_PROFILE=contract_ZeroExV4Adapter_49af forge build || {
  echo "❌ Failed to build ZeroExV4Adapter"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_ZeroExV4Adapter_49af forge build"
}
echo "✅ Built ZeroExV4Adapter"
echo ""

echo "Building NoDepegOnRedeemSharesForSpecificAssetsPolicy (contract_NoDepegOnRedeemSharesForSpecificAssetsPolicy_96ef)"
FOUNDRY_PROFILE=contract_NoDepegOnRedeemSharesForSpecificAssetsPolicy_96ef forge build || {
  echo "❌ Failed to build NoDepegOnRedeemSharesForSpecificAssetsPolicy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_NoDepegOnRedeemSharesForSpecificAssetsPolicy_96ef forge build"
}
echo "✅ Built NoDepegOnRedeemSharesForSpecificAssetsPolicy"
echo ""

echo "Building FeeManager (contract_FeeManager_af0d)"
FOUNDRY_PROFILE=contract_FeeManager_af0d forge build || {
  echo "❌ Failed to build FeeManager"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_FeeManager_af0d forge build"
}
echo "✅ Built FeeManager"
echo ""

echo "Building ExitRateBurnFee (contract_ExitRateBurnFee_06b1)"
FOUNDRY_PROFILE=contract_ExitRateBurnFee_06b1 forge build || {
  echo "❌ Failed to build ExitRateBurnFee"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_ExitRateBurnFee_06b1 forge build"
}
echo "✅ Built ExitRateBurnFee"
echo ""

echo "Building ValueInterpreter (contract_ValueInterpreter_d7b0)"
FOUNDRY_PROFILE=contract_ValueInterpreter_d7b0 forge build || {
  echo "❌ Failed to build ValueInterpreter"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_ValueInterpreter_d7b0 forge build"
}
echo "✅ Built ValueInterpreter"
echo ""

echo "Building ThreeOneThirdAdapter (contract_ThreeOneThirdAdapter_5a1c)"
FOUNDRY_PROFILE=contract_ThreeOneThirdAdapter_5a1c forge build || {
  echo "❌ Failed to build ThreeOneThirdAdapter"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_ThreeOneThirdAdapter_5a1c forge build"
}
echo "✅ Built ThreeOneThirdAdapter"
echo ""

echo "Building FundDeployer (contract_FundDeployer_4f1c)"
FOUNDRY_PROFILE=contract_FundDeployer_4f1c forge build || {
  echo "❌ Failed to build FundDeployer"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_FundDeployer_4f1c forge build"
}
echo "✅ Built FundDeployer"
echo ""

echo "Building DisallowedAdapterIncomingAssetsPolicy (contract_DisallowedAdapterIncomingAssetsPolicy_5e21)"
FOUNDRY_PROFILE=contract_DisallowedAdapterIncomingAssetsPolicy_5e21 forge build || {
  echo "❌ Failed to build DisallowedAdapterIncomingAssetsPolicy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_DisallowedAdapterIncomingAssetsPolicy_5e21 forge build"
}
echo "✅ Built DisallowedAdapterIncomingAssetsPolicy"
echo ""

echo "Building ExternalPositionManager (contract_ExternalPositionManager_1e3d)"
FOUNDRY_PROFILE=contract_ExternalPositionManager_1e3d forge build || {
  echo "❌ Failed to build ExternalPositionManager"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_ExternalPositionManager_1e3d forge build"
}
echo "✅ Built ExternalPositionManager"
echo ""

echo "Building ArbitraryLoanPositionLib (contract_ArbitraryLoanPositionLib_73cb)"
FOUNDRY_PROFILE=contract_ArbitraryLoanPositionLib_73cb forge build || {
  echo "❌ Failed to build ArbitraryLoanPositionLib"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_ArbitraryLoanPositionLib_73cb forge build"
}
echo "✅ Built ArbitraryLoanPositionLib"
echo ""

echo "Building StaderStakingAdapter (contract_StaderStakingAdapter_7f1b)"
FOUNDRY_PROFILE=contract_StaderStakingAdapter_7f1b forge build || {
  echo "❌ Failed to build StaderStakingAdapter"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_StaderStakingAdapter_7f1b forge build"
}
echo "✅ Built StaderStakingAdapter"
echo ""

echo "Building EtherFiEthPriceFeed (contract_EtherFiEthPriceFeed_3110)"
FOUNDRY_PROFILE=contract_EtherFiEthPriceFeed_3110 forge build || {
  echo "❌ Failed to build EtherFiEthPriceFeed"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_EtherFiEthPriceFeed_3110 forge build"
}
echo "✅ Built EtherFiEthPriceFeed"
echo ""

echo "Building ExitRateDirectFee (contract_ExitRateDirectFee_3a09)"
FOUNDRY_PROFILE=contract_ExitRateDirectFee_3a09 forge build || {
  echo "❌ Failed to build ExitRateDirectFee"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_ExitRateDirectFee_3a09 forge build"
}
echo "✅ Built ExitRateDirectFee"
echo ""

echo "Building AllowedExternalPositionTypesPerManagerPolicy (contract_AllowedExternalPositionTypesPerManagerPolicy_47fb)"
FOUNDRY_PROFILE=contract_AllowedExternalPositionTypesPerManagerPolicy_47fb forge build || {
  echo "❌ Failed to build AllowedExternalPositionTypesPerManagerPolicy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_AllowedExternalPositionTypesPerManagerPolicy_47fb forge build"
}
echo "✅ Built AllowedExternalPositionTypesPerManagerPolicy"
echo ""

echo "Building ConvexVotingPositionParser (contract_ConvexVotingPositionParser_4619)"
FOUNDRY_PROFILE=contract_ConvexVotingPositionParser_4619 forge build || {
  echo "❌ Failed to build ConvexVotingPositionParser"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_ConvexVotingPositionParser_4619 forge build"
}
echo "✅ Built ConvexVotingPositionParser"
echo ""

echo "Building ConvexVotingPositionLib (contract_ConvexVotingPositionLib_12fa)"
FOUNDRY_PROFILE=contract_ConvexVotingPositionLib_12fa forge build || {
  echo "❌ Failed to build ConvexVotingPositionLib"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_ConvexVotingPositionLib_12fa forge build"
}
echo "✅ Built ConvexVotingPositionLib"
echo ""

echo "Building NonStandardPrecisionSimulatedAggregator (contract_NonStandardPrecisionSimulatedAggregator_ca28)"
FOUNDRY_PROFILE=contract_NonStandardPrecisionSimulatedAggregator_ca28 forge build || {
  echo "❌ Failed to build NonStandardPrecisionSimulatedAggregator"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_NonStandardPrecisionSimulatedAggregator_ca28 forge build"
}
echo "✅ Built NonStandardPrecisionSimulatedAggregator"
echo ""

echo "Building ERC4626Adapter (contract_ERC4626Adapter_64fa)"
FOUNDRY_PROFILE=contract_ERC4626Adapter_64fa forge build || {
  echo "❌ Failed to build ERC4626Adapter"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_ERC4626Adapter_64fa forge build"
}
echo "✅ Built ERC4626Adapter"
echo ""

echo "Building AllowedAdaptersPolicy (contract_AllowedAdaptersPolicy_720e)"
FOUNDRY_PROFILE=contract_AllowedAdaptersPolicy_720e forge build || {
  echo "❌ Failed to build AllowedAdaptersPolicy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_AllowedAdaptersPolicy_720e forge build"
}
echo "✅ Built AllowedAdaptersPolicy"
echo ""

echo "Building FundValueCalculatorRouter (contract_FundValueCalculatorRouter_7c72)"
FOUNDRY_PROFILE=contract_FundValueCalculatorRouter_7c72 forge build || {
  echo "❌ Failed to build FundValueCalculatorRouter"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_FundValueCalculatorRouter_7c72 forge build"
}
echo "✅ Built FundValueCalculatorRouter"
echo ""

echo "Building AaveV3Adapter (contract_AaveV3Adapter_9cfb)"
FOUNDRY_PROFILE=contract_AaveV3Adapter_9cfb forge build || {
  echo "❌ Failed to build AaveV3Adapter"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_AaveV3Adapter_9cfb forge build"
}
echo "✅ Built AaveV3Adapter"
echo ""

echo "Building PeggedDerivativesPriceFeed (contract_PeggedDerivativesPriceFeed_8653)"
FOUNDRY_PROFILE=contract_PeggedDerivativesPriceFeed_8653 forge build || {
  echo "❌ Failed to build PeggedDerivativesPriceFeed"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_PeggedDerivativesPriceFeed_8653 forge build"
}
echo "✅ Built PeggedDerivativesPriceFeed"
echo ""

echo "Building UintListRegistry (contract_UintListRegistry_6ffd)"
FOUNDRY_PROFILE=contract_UintListRegistry_6ffd forge build || {
  echo "❌ Failed to build UintListRegistry"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_UintListRegistry_6ffd forge build"
}
echo "✅ Built UintListRegistry"
echo ""

echo "Building GasRelayPaymasterLib (contract_GasRelayPaymasterLib_131c)"
FOUNDRY_PROFILE=contract_GasRelayPaymasterLib_131c forge build || {
  echo "❌ Failed to build GasRelayPaymasterLib"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_GasRelayPaymasterLib_131c forge build"
}
echo "✅ Built GasRelayPaymasterLib"
echo ""

echo "Building OnlyUntrackDustOrPricelessAssetsPolicy (contract_OnlyUntrackDustOrPricelessAssetsPolicy_747b)"
FOUNDRY_PROFILE=contract_OnlyUntrackDustOrPricelessAssetsPolicy_747b forge build || {
  echo "❌ Failed to build OnlyUntrackDustOrPricelessAssetsPolicy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_OnlyUntrackDustOrPricelessAssetsPolicy_747b forge build"
}
echo "✅ Built OnlyUntrackDustOrPricelessAssetsPolicy"
echo ""

echo "Building TransferAssetsAdapter (contract_TransferAssetsAdapter_e030)"
FOUNDRY_PROFILE=contract_TransferAssetsAdapter_e030 forge build || {
  echo "❌ Failed to build TransferAssetsAdapter"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_TransferAssetsAdapter_e030 forge build"
}
echo "✅ Built TransferAssetsAdapter"
echo ""

echo "Building DispatcherOwnedBeaconFactory (contract_DispatcherOwnedBeaconFactory_d6e8)"
FOUNDRY_PROFILE=contract_DispatcherOwnedBeaconFactory_d6e8 forge build || {
  echo "❌ Failed to build DispatcherOwnedBeaconFactory"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_DispatcherOwnedBeaconFactory_d6e8 forge build"
}
echo "✅ Built DispatcherOwnedBeaconFactory"
echo ""

echo "Building OnlyRemoveDustExternalPositionPolicy (contract_OnlyRemoveDustExternalPositionPolicy_966e)"
FOUNDRY_PROFILE=contract_OnlyRemoveDustExternalPositionPolicy_966e forge build || {
  echo "❌ Failed to build OnlyRemoveDustExternalPositionPolicy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_OnlyRemoveDustExternalPositionPolicy_966e forge build"
}
echo "✅ Built OnlyRemoveDustExternalPositionPolicy"
echo ""

echo "Building ERC4626RateAggregatorFactory (contract_ERC4626RateAggregatorFactory_00f6)"
FOUNDRY_PROFILE=contract_ERC4626RateAggregatorFactory_00f6 forge build || {
  echo "❌ Failed to build ERC4626RateAggregatorFactory"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_ERC4626RateAggregatorFactory_00f6 forge build"
}
echo "✅ Built ERC4626RateAggregatorFactory"
echo ""

echo "Building AaveV3ATokenListOwner (contract_AaveV3ATokenListOwner_cfe2)"
FOUNDRY_PROFILE=contract_AaveV3ATokenListOwner_cfe2 forge build || {
  echo "❌ Failed to build AaveV3ATokenListOwner"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_AaveV3ATokenListOwner_cfe2 forge build"
}
echo "✅ Built AaveV3ATokenListOwner"
echo ""

echo "Building UnpermissionedActionsWrapper (contract_UnpermissionedActionsWrapper_cfab)"
FOUNDRY_PROFILE=contract_UnpermissionedActionsWrapper_cfab forge build || {
  echo "❌ Failed to build UnpermissionedActionsWrapper"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_UnpermissionedActionsWrapper_cfab forge build"
}
echo "✅ Built UnpermissionedActionsWrapper"
echo ""

echo "Building StaderWithdrawalsPositionLib (contract_StaderWithdrawalsPositionLib_5cf4)"
FOUNDRY_PROFILE=contract_StaderWithdrawalsPositionLib_5cf4 forge build || {
  echo "❌ Failed to build StaderWithdrawalsPositionLib"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_StaderWithdrawalsPositionLib_5cf4 forge build"
}
echo "✅ Built StaderWithdrawalsPositionLib"
echo ""

echo "Building UniswapV3LiquidityPositionParser (contract_UniswapV3LiquidityPositionParser_2380)"
FOUNDRY_PROFILE=contract_UniswapV3LiquidityPositionParser_2380 forge build || {
  echo "❌ Failed to build UniswapV3LiquidityPositionParser"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_UniswapV3LiquidityPositionParser_2380 forge build"
}
echo "✅ Built UniswapV3LiquidityPositionParser"
echo ""

echo "Building GlobalConfigProxy (contract_GlobalConfigProxy_5611)"
FOUNDRY_PROFILE=contract_GlobalConfigProxy_5611 forge build || {
  echo "❌ Failed to build GlobalConfigProxy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_GlobalConfigProxy_5611 forge build"
}
echo "✅ Built GlobalConfigProxy"
echo ""

echo "Building SharesSplitterFactory (contract_SharesSplitterFactory_fc8e)"
FOUNDRY_PROFILE=contract_SharesSplitterFactory_fc8e forge build || {
  echo "❌ Failed to build SharesSplitterFactory"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_SharesSplitterFactory_fc8e forge build"
}
echo "✅ Built SharesSplitterFactory"
echo ""

echo "Building GasRelayPaymasterFactory (contract_GasRelayPaymasterFactory_846b)"
FOUNDRY_PROFILE=contract_GasRelayPaymasterFactory_846b forge build || {
  echo "❌ Failed to build GasRelayPaymasterFactory"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_GasRelayPaymasterFactory_846b forge build"
}
echo "✅ Built GasRelayPaymasterFactory"
echo ""

echo "Building ParaSwapV6Adapter (contract_ParaSwapV6Adapter_b3ec)"
FOUNDRY_PROFILE=contract_ParaSwapV6Adapter_b3ec forge build || {
  echo "❌ Failed to build ParaSwapV6Adapter"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_ParaSwapV6Adapter_b3ec forge build"
}
echo "✅ Built ParaSwapV6Adapter"
echo ""

echo "Building LidoWithdrawalsPositionParser (contract_LidoWithdrawalsPositionParser_5010)"
FOUNDRY_PROFILE=contract_LidoWithdrawalsPositionParser_5010 forge build || {
  echo "❌ Failed to build LidoWithdrawalsPositionParser"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_LidoWithdrawalsPositionParser_5010 forge build"
}
echo "✅ Built LidoWithdrawalsPositionParser"
echo ""

echo "Building AllowedAdapterIncomingAssetsPolicy (contract_AllowedAdapterIncomingAssetsPolicy_2f0e)"
FOUNDRY_PROFILE=contract_AllowedAdapterIncomingAssetsPolicy_2f0e forge build || {
  echo "❌ Failed to build AllowedAdapterIncomingAssetsPolicy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_AllowedAdapterIncomingAssetsPolicy_2f0e forge build"
}
echo "✅ Built AllowedAdapterIncomingAssetsPolicy"
echo ""

echo "Building GlobalConfigLib (contract_GlobalConfigLib_6682)"
FOUNDRY_PROFILE=contract_GlobalConfigLib_6682 forge build || {
  echo "❌ Failed to build GlobalConfigLib"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_GlobalConfigLib_6682 forge build"
}
echo "✅ Built GlobalConfigLib"
echo ""

echo "Building AllowedAssetsForRedemptionPolicy (contract_AllowedAssetsForRedemptionPolicy_823c)"
FOUNDRY_PROFILE=contract_AllowedAssetsForRedemptionPolicy_823c forge build || {
  echo "❌ Failed to build AllowedAssetsForRedemptionPolicy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_AllowedAssetsForRedemptionPolicy_823c forge build"
}
echo "✅ Built AllowedAssetsForRedemptionPolicy"
echo ""

echo "Building ArbitraryLoanPositionParser (contract_ArbitraryLoanPositionParser_e959)"
FOUNDRY_PROFILE=contract_ArbitraryLoanPositionParser_e959 forge build || {
  echo "❌ Failed to build ArbitraryLoanPositionParser"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_ArbitraryLoanPositionParser_e959 forge build"
}
echo "✅ Built ArbitraryLoanPositionParser"
echo ""

echo "Building ManualValueOracleFactory (contract_ManualValueOracleFactory_0edb)"
FOUNDRY_PROFILE=contract_ManualValueOracleFactory_0edb forge build || {
  echo "❌ Failed to build ManualValueOracleFactory"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_ManualValueOracleFactory_0edb forge build"
}
echo "✅ Built ManualValueOracleFactory"
echo ""

echo "Building MinSharesSupplyFee (contract_MinSharesSupplyFee_bc9d)"
FOUNDRY_PROFILE=contract_MinSharesSupplyFee_bc9d forge build || {
  echo "❌ Failed to build MinSharesSupplyFee"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_MinSharesSupplyFee_bc9d forge build"
}
echo "✅ Built MinSharesSupplyFee"
echo ""

echo "Building EntranceRateDirectFee (contract_EntranceRateDirectFee_fb8d)"
FOUNDRY_PROFILE=contract_EntranceRateDirectFee_fb8d forge build || {
  echo "❌ Failed to build EntranceRateDirectFee"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_EntranceRateDirectFee_fb8d forge build"
}
echo "✅ Built EntranceRateDirectFee"
echo ""

echo "Building SharePriceThrottledAssetManagerLib (contract_SharePriceThrottledAssetManagerLib_fde8)"
FOUNDRY_PROFILE=contract_SharePriceThrottledAssetManagerLib_fde8 forge build || {
  echo "❌ Failed to build SharePriceThrottledAssetManagerLib"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_SharePriceThrottledAssetManagerLib_fde8 forge build"
}
echo "✅ Built SharePriceThrottledAssetManagerLib"
echo ""

echo "Building ERC4626PriceFeed (contract_ERC4626PriceFeed_66aa)"
FOUNDRY_PROFILE=contract_ERC4626PriceFeed_66aa forge build || {
  echo "❌ Failed to build ERC4626PriceFeed"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_ERC4626PriceFeed_66aa forge build"
}
echo "✅ Built ERC4626PriceFeed"
echo ""

echo "Building ComptrollerLib (contract_ComptrollerLib_03f7)"
FOUNDRY_PROFILE=contract_ComptrollerLib_03f7 forge build || {
  echo "❌ Failed to build ComptrollerLib"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_ComptrollerLib_03f7 forge build"
}
echo "✅ Built ComptrollerLib"
echo ""

echo "Building MinMaxInvestmentPolicy (contract_MinMaxInvestmentPolicy_ebda)"
FOUNDRY_PROFILE=contract_MinMaxInvestmentPolicy_ebda forge build || {
  echo "❌ Failed to build MinMaxInvestmentPolicy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_MinMaxInvestmentPolicy_ebda forge build"
}
echo "✅ Built MinMaxInvestmentPolicy"
echo ""

echo "Building GatedRedemptionQueueSharesWrapperLib (contract_GatedRedemptionQueueSharesWrapperLib_e971)"
FOUNDRY_PROFILE=contract_GatedRedemptionQueueSharesWrapperLib_e971 forge build || {
  echo "❌ Failed to build GatedRedemptionQueueSharesWrapperLib"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_GatedRedemptionQueueSharesWrapperLib_e971 forge build"
}
echo "✅ Built GatedRedemptionQueueSharesWrapperLib"
echo ""

echo "Building SharePriceThrottledAssetManagerFactory (contract_SharePriceThrottledAssetManagerFactory_0883)"
FOUNDRY_PROFILE=contract_SharePriceThrottledAssetManagerFactory_0883 forge build || {
  echo "❌ Failed to build SharePriceThrottledAssetManagerFactory"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_SharePriceThrottledAssetManagerFactory_0883 forge build"
}
echo "✅ Built SharePriceThrottledAssetManagerFactory"
echo ""

echo "Building StaderSDPriceFeed (contract_StaderSDPriceFeed_9938)"
FOUNDRY_PROFILE=contract_StaderSDPriceFeed_9938 forge build || {
  echo "❌ Failed to build StaderSDPriceFeed"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_StaderSDPriceFeed_9938 forge build"
}
echo "✅ Built StaderSDPriceFeed"
echo ""

echo "Building UniswapV3LiquidityPositionLib (contract_UniswapV3LiquidityPositionLib_20a2)"
FOUNDRY_PROFILE=contract_UniswapV3LiquidityPositionLib_20a2 forge build || {
  echo "❌ Failed to build UniswapV3LiquidityPositionLib"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_UniswapV3LiquidityPositionLib_20a2 forge build"
}
echo "✅ Built UniswapV3LiquidityPositionLib"
echo ""

echo "Building UsdEthSimulatedAggregator (contract_UsdEthSimulatedAggregator_9579)"
FOUNDRY_PROFILE=contract_UsdEthSimulatedAggregator_9579 forge build || {
  echo "❌ Failed to build UsdEthSimulatedAggregator"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_UsdEthSimulatedAggregator_9579 forge build"
}
echo "✅ Built UsdEthSimulatedAggregator"
echo ""

echo "Building AddressListRegistry (contract_AddressListRegistry_4eb4)"
FOUNDRY_PROFILE=contract_AddressListRegistry_4eb4 forge build || {
  echo "❌ Failed to build AddressListRegistry"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_AddressListRegistry_4eb4 forge build"
}
echo "✅ Built AddressListRegistry"
echo ""

echo "Building ProtocolFeeReserveProxy (contract_ProtocolFeeReserveProxy_b746)"
FOUNDRY_PROFILE=contract_ProtocolFeeReserveProxy_b746 forge build || {
  echo "❌ Failed to build ProtocolFeeReserveProxy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_ProtocolFeeReserveProxy_b746 forge build"
}
echo "✅ Built ProtocolFeeReserveProxy"
echo ""

echo "Building SmarDexUsdnNativeRateUsdAggregator (contract_SmarDexUsdnNativeRateUsdAggregator_d500)"
FOUNDRY_PROFILE=contract_SmarDexUsdnNativeRateUsdAggregator_d500 forge build || {
  echo "❌ Failed to build SmarDexUsdnNativeRateUsdAggregator"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_SmarDexUsdnNativeRateUsdAggregator_d500 forge build"
}
echo "✅ Built SmarDexUsdnNativeRateUsdAggregator"
echo ""

echo "Building Dispatcher (contract_Dispatcher_c3dc)"
FOUNDRY_PROFILE=contract_Dispatcher_c3dc forge build || {
  echo "❌ Failed to build Dispatcher"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_Dispatcher_c3dc forge build"
}
echo "✅ Built Dispatcher"
echo ""

echo "Building IntegrationManager (contract_IntegrationManager_3132)"
FOUNDRY_PROFILE=contract_IntegrationManager_3132 forge build || {
  echo "❌ Failed to build IntegrationManager"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_IntegrationManager_3132 forge build"
}
echo "✅ Built IntegrationManager"
echo ""

echo "Building ArbitraryLoanTotalNominalDeltaOracleModule (contract_ArbitraryLoanTotalNominalDeltaOracleModule_7f2a)"
FOUNDRY_PROFILE=contract_ArbitraryLoanTotalNominalDeltaOracleModule_7f2a forge build || {
  echo "❌ Failed to build ArbitraryLoanTotalNominalDeltaOracleModule"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_ArbitraryLoanTotalNominalDeltaOracleModule_7f2a forge build"
}
echo "✅ Built ArbitraryLoanTotalNominalDeltaOracleModule"
echo ""

echo "Building PerformanceFee (contract_PerformanceFee_fedc)"
FOUNDRY_PROFILE=contract_PerformanceFee_fedc forge build || {
  echo "❌ Failed to build PerformanceFee"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_PerformanceFee_fedc forge build"
}
echo "✅ Built PerformanceFee"
echo ""

echo "Building AllowedExternalPositionTypesPolicy (contract_AllowedExternalPositionTypesPolicy_9e07)"
FOUNDRY_PROFILE=contract_AllowedExternalPositionTypesPolicy_9e07 forge build || {
  echo "❌ Failed to build AllowedExternalPositionTypesPolicy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_AllowedExternalPositionTypesPolicy_9e07 forge build"
}
echo "✅ Built AllowedExternalPositionTypesPolicy"
echo ""

echo "Building AaveV3DebtPositionParser (contract_AaveV3DebtPositionParser_4010)"
FOUNDRY_PROFILE=contract_AaveV3DebtPositionParser_4010 forge build || {
  echo "❌ Failed to build AaveV3DebtPositionParser"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_AaveV3DebtPositionParser_4010 forge build"
}
echo "✅ Built AaveV3DebtPositionParser"
echo ""

echo "Building EnzymeVaultPriceFeed (contract_EnzymeVaultPriceFeed_2a07)"
FOUNDRY_PROFILE=contract_EnzymeVaultPriceFeed_2a07 forge build || {
  echo "❌ Failed to build EnzymeVaultPriceFeed"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_EnzymeVaultPriceFeed_2a07 forge build"
}
echo "✅ Built EnzymeVaultPriceFeed"
echo ""

echo "Building StaderWithdrawalsPositionParser (contract_StaderWithdrawalsPositionParser_aefe)"
FOUNDRY_PROFILE=contract_StaderWithdrawalsPositionParser_aefe forge build || {
  echo "❌ Failed to build StaderWithdrawalsPositionParser"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_StaderWithdrawalsPositionParser_aefe forge build"
}
echo "✅ Built StaderWithdrawalsPositionParser"
echo ""

echo "Building SingleAssetRedemptionQueueLib (contract_SingleAssetRedemptionQueueLib_0012)"
FOUNDRY_PROFILE=contract_SingleAssetRedemptionQueueLib_0012 forge build || {
  echo "❌ Failed to build SingleAssetRedemptionQueueLib"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_SingleAssetRedemptionQueueLib_0012 forge build"
}
echo "✅ Built SingleAssetRedemptionQueueLib"
echo ""

echo "Building PeggedRateDeviationAggregatorFactory (contract_PeggedRateDeviationAggregatorFactory_d718)"
FOUNDRY_PROFILE=contract_PeggedRateDeviationAggregatorFactory_d718 forge build || {
  echo "❌ Failed to build PeggedRateDeviationAggregatorFactory"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_PeggedRateDeviationAggregatorFactory_d718 forge build"
}
echo "✅ Built PeggedRateDeviationAggregatorFactory"
echo ""

echo "Building AllowedDepositRecipientsPolicy (contract_AllowedDepositRecipientsPolicy_a66b)"
FOUNDRY_PROFILE=contract_AllowedDepositRecipientsPolicy_a66b forge build || {
  echo "❌ Failed to build AllowedDepositRecipientsPolicy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_AllowedDepositRecipientsPolicy_a66b forge build"
}
echo "✅ Built AllowedDepositRecipientsPolicy"
echo ""

echo "Building UniswapV3Adapter (contract_UniswapV3Adapter_ed6a)"
FOUNDRY_PROFILE=contract_UniswapV3Adapter_ed6a forge build || {
  echo "❌ Failed to build UniswapV3Adapter"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_UniswapV3Adapter_ed6a forge build"
}
echo "✅ Built UniswapV3Adapter"
echo ""

echo "Building AllowedAdaptersPerManagerPolicy (contract_AllowedAdaptersPerManagerPolicy_a450)"
FOUNDRY_PROFILE=contract_AllowedAdaptersPerManagerPolicy_a450 forge build || {
  echo "❌ Failed to build AllowedAdaptersPerManagerPolicy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_AllowedAdaptersPerManagerPolicy_a450 forge build"
}
echo "✅ Built AllowedAdaptersPerManagerPolicy"
echo ""

echo "Building EnzymeV4VaultAdapter (contract_EnzymeV4VaultAdapter_2b4f)"
FOUNDRY_PROFILE=contract_EnzymeV4VaultAdapter_2b4f forge build || {
  echo "❌ Failed to build EnzymeV4VaultAdapter"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_EnzymeV4VaultAdapter_2b4f forge build"
}
echo "✅ Built EnzymeV4VaultAdapter"
echo ""

echo "Building MinAssetBalancesPostRedemptionPolicy (contract_MinAssetBalancesPostRedemptionPolicy_58c0)"
FOUNDRY_PROFILE=contract_MinAssetBalancesPostRedemptionPolicy_58c0 forge build || {
  echo "❌ Failed to build MinAssetBalancesPostRedemptionPolicy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_MinAssetBalancesPostRedemptionPolicy_58c0 forge build"
}
echo "✅ Built MinAssetBalancesPostRedemptionPolicy"
echo ""

echo "Building PolicyManager (contract_PolicyManager_adf5)"
FOUNDRY_PROFILE=contract_PolicyManager_adf5 forge build || {
  echo "❌ Failed to build PolicyManager"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_PolicyManager_adf5 forge build"
}
echo "✅ Built PolicyManager"
echo ""

echo "Building DepositWrapper (contract_DepositWrapper_65bb)"
FOUNDRY_PROFILE=contract_DepositWrapper_65bb forge build || {
  echo "❌ Failed to build DepositWrapper"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_DepositWrapper_65bb forge build"
}
echo "✅ Built DepositWrapper"
echo ""

echo "Building AavePriceFeed (contract_AavePriceFeed_e9cf)"
FOUNDRY_PROFILE=contract_AavePriceFeed_e9cf forge build || {
  echo "❌ Failed to build AavePriceFeed"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_AavePriceFeed_e9cf forge build"
}
echo "✅ Built AavePriceFeed"
echo ""

echo "Building PendleV2Adapter (contract_PendleV2Adapter_e77b)"
FOUNDRY_PROFILE=contract_PendleV2Adapter_e77b forge build || {
  echo "❌ Failed to build PendleV2Adapter"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_PendleV2Adapter_e77b forge build"
}
echo "✅ Built PendleV2Adapter"
echo ""

echo "Building ExternalPositionFactory (contract_ExternalPositionFactory_0aac)"
FOUNDRY_PROFILE=contract_ExternalPositionFactory_0aac forge build || {
  echo "❌ Failed to build ExternalPositionFactory"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_ExternalPositionFactory_0aac forge build"
}
echo "✅ Built ExternalPositionFactory"
echo ""

echo "Building SingleAssetRedemptionQueueFactory (contract_SingleAssetRedemptionQueueFactory_fe84)"
FOUNDRY_PROFILE=contract_SingleAssetRedemptionQueueFactory_fe84 forge build || {
  echo "❌ Failed to build SingleAssetRedemptionQueueFactory"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_SingleAssetRedemptionQueueFactory_fe84 forge build"
}
echo "✅ Built SingleAssetRedemptionQueueFactory"
echo ""

echo "Building AllowedRedeemersForSpecificAssetsPolicy (contract_AllowedRedeemersForSpecificAssetsPolicy_ed4a)"
FOUNDRY_PROFILE=contract_AllowedRedeemersForSpecificAssetsPolicy_ed4a forge build || {
  echo "❌ Failed to build AllowedRedeemersForSpecificAssetsPolicy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_AllowedRedeemersForSpecificAssetsPolicy_ed4a forge build"
}
echo "✅ Built AllowedRedeemersForSpecificAssetsPolicy"
echo ""

echo "Building AllowedSharesTransferRecipientsPolicy (contract_AllowedSharesTransferRecipientsPolicy_ebe3)"
FOUNDRY_PROFILE=contract_AllowedSharesTransferRecipientsPolicy_ebe3 forge build || {
  echo "❌ Failed to build AllowedSharesTransferRecipientsPolicy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_AllowedSharesTransferRecipientsPolicy_ebe3 forge build"
}
echo "✅ Built AllowedSharesTransferRecipientsPolicy"
echo ""

echo "Building ProtocolFeeTracker (contract_ProtocolFeeTracker_e979)"
FOUNDRY_PROFILE=contract_ProtocolFeeTracker_e979 forge build || {
  echo "❌ Failed to build ProtocolFeeTracker"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_ProtocolFeeTracker_e979 forge build"
}
echo "✅ Built ProtocolFeeTracker"
echo ""

echo "Building AaveV3FlashLoanAssetManagerLib (contract_AaveV3FlashLoanAssetManagerLib_8aa6)"
FOUNDRY_PROFILE=contract_AaveV3FlashLoanAssetManagerLib_8aa6 forge build || {
  echo "❌ Failed to build AaveV3FlashLoanAssetManagerLib"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_AaveV3FlashLoanAssetManagerLib_8aa6 forge build"
}
echo "✅ Built AaveV3FlashLoanAssetManagerLib"
echo ""

echo "Building ChainlinkLikeWstethPriceFeed (contract_ChainlinkLikeWstethPriceFeed_9282)"
FOUNDRY_PROFILE=contract_ChainlinkLikeWstethPriceFeed_9282 forge build || {
  echo "❌ Failed to build ChainlinkLikeWstethPriceFeed"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_ChainlinkLikeWstethPriceFeed_9282 forge build"
}
echo "✅ Built ChainlinkLikeWstethPriceFeed"
echo ""

echo "Building ManagementFee (contract_ManagementFee_faf2)"
FOUNDRY_PROFILE=contract_ManagementFee_faf2 forge build || {
  echo "❌ Failed to build ManagementFee"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_ManagementFee_faf2 forge build"
}
echo "✅ Built ManagementFee"
echo ""

echo "Building LidoWithdrawalsPositionLib (contract_LidoWithdrawalsPositionLib_a511)"
FOUNDRY_PROFILE=contract_LidoWithdrawalsPositionLib_a511 forge build || {
  echo "❌ Failed to build LidoWithdrawalsPositionLib"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_LidoWithdrawalsPositionLib_a511 forge build"
}
echo "✅ Built LidoWithdrawalsPositionLib"
echo ""

echo "Building ConvertedQuoteAggregatorFactory (contract_ConvertedQuoteAggregatorFactory_8f1e)"
FOUNDRY_PROFILE=contract_ConvertedQuoteAggregatorFactory_8f1e forge build || {
  echo "❌ Failed to build ConvertedQuoteAggregatorFactory"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_ConvertedQuoteAggregatorFactory_8f1e forge build"
}
echo "✅ Built ConvertedQuoteAggregatorFactory"
echo ""

echo "Building VaultLib (contract_VaultLib_891d)"
FOUNDRY_PROFILE=contract_VaultLib_891d forge build || {
  echo "❌ Failed to build VaultLib"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_VaultLib_891d forge build"
}
echo "✅ Built VaultLib"
echo ""

echo "Building EntranceRateBurnFee (contract_EntranceRateBurnFee_cdec)"
FOUNDRY_PROFILE=contract_EntranceRateBurnFee_cdec forge build || {
  echo "❌ Failed to build EntranceRateBurnFee"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_EntranceRateBurnFee_cdec forge build"
}
echo "✅ Built EntranceRateBurnFee"
echo ""

echo "Building CumulativeSlippageTolerancePolicy (contract_CumulativeSlippageTolerancePolicy_3a49)"
FOUNDRY_PROFILE=contract_CumulativeSlippageTolerancePolicy_3a49 forge build || {
  echo "❌ Failed to build CumulativeSlippageTolerancePolicy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_CumulativeSlippageTolerancePolicy_3a49 forge build"
}
echo "✅ Built CumulativeSlippageTolerancePolicy"
echo ""

echo "Building ProtocolFeeReserveLib (contract_ProtocolFeeReserveLib_a0ed)"
FOUNDRY_PROFILE=contract_ProtocolFeeReserveLib_a0ed forge build || {
  echo "❌ Failed to build ProtocolFeeReserveLib"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_ProtocolFeeReserveLib_a0ed forge build"
}
echo "✅ Built ProtocolFeeReserveLib"
echo ""

echo "Building GatedRedemptionQueueSharesWrapperFactory (contract_GatedRedemptionQueueSharesWrapperFactory_70c1)"
FOUNDRY_PROFILE=contract_GatedRedemptionQueueSharesWrapperFactory_70c1 forge build || {
  echo "❌ Failed to build GatedRedemptionQueueSharesWrapperFactory"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_GatedRedemptionQueueSharesWrapperFactory_70c1 forge build"
}
echo "✅ Built GatedRedemptionQueueSharesWrapperFactory"
echo ""

echo "Building AaveV3DebtPositionLib (contract_AaveV3DebtPositionLib_e72b)"
FOUNDRY_PROFILE=contract_AaveV3DebtPositionLib_e72b forge build || {
  echo "❌ Failed to build AaveV3DebtPositionLib"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_AaveV3DebtPositionLib_e72b forge build"
}
echo "✅ Built AaveV3DebtPositionLib"
echo ""

echo "Building OneInchV5Adapter (contract_OneInchV5Adapter_6c62)"
FOUNDRY_PROFILE=contract_OneInchV5Adapter_6c62 forge build || {
  echo "❌ Failed to build OneInchV5Adapter"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_OneInchV5Adapter_6c62 forge build"
}
echo "✅ Built OneInchV5Adapter"
echo ""

echo "Building FundValueCalculator (contract_FundValueCalculator_490e)"
FOUNDRY_PROFILE=contract_FundValueCalculator_490e forge build || {
  echo "❌ Failed to build FundValueCalculator"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_FundValueCalculator_490e forge build"
}
echo "✅ Built FundValueCalculator"
echo ""

echo "Building ProtocolFeeReserveLib (contract_ProtocolFeeReserveLib_d462)"
FOUNDRY_PROFILE=contract_ProtocolFeeReserveLib_d462 forge build || {
  echo "❌ Failed to build ProtocolFeeReserveLib"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_ProtocolFeeReserveLib_d462 forge build"
}
echo "✅ Built ProtocolFeeReserveLib"
echo ""

echo "================================"
echo "Build complete - each contract compiled independently"
echo "================================"
